### ISSUE TITLE
Tests for the new JULIA_DEPOT_PATH system

### ISSUE THREAD

**Issue by jlperla** [ubcecon/syzygy#3]
Lets start by actually deleting the `environments` and `registries` for the jovyan account to make sure there is no chance that weird things get picked up.  Also, lets just leave the jupyter user with no seeding of anything julia related.
- [x] Start up the REPL and go `] add XXX` for something that we know has the latest version in the shared repositories.  This probably will clone the registries to their local machine, but it should not need to install the package locally or precompile
- [x] Now add in a **different** version of that same package which is in our shared repository.  This should install a package local to the users `.julia`.  For this, you may to create a new project just so it doesn't break the global manifest.
- [x] Then add in a new package that is not in the shared depot, and make sure it does install locally.
- [x] Open one of our jupyter notebooks for quantecon, and have it activate, instantiate, etc. the QE project files.  This should not install or precompile anything

**Comment by arnavs** [comment]
Test results. And think these are good; these are the experiments I was running on my own.  

1. Will make us a registry, and use the shared QuantEcon. 

```
(v1.0) pkg> st
    Status `~/.julia/environments/v1.0/Project.toml`
  [fcd29c91] QuantEcon v0.15.0

julia> using QuantEcon

julia> pathof(QuantEcon)
"/home/jovyan/.julia/packages/QuantEcon/7w41U/src/QuantEcon.jl"

shell> pwd
/home/jupyter
```

2. Yup. 

```
(v1.0) pkg> add QuantEcon@0.14.3
 Resolving package versions...
 Installed Nullables ─ v0.0.8
 Installed QuantEcon ─ v0.14.3
  Updating `~/.julia/environments/v1.0/Project.toml`
  [fcd29c91] ↓ QuantEcon v0.15.0 ⇒ v0.14.3
  Updating `~/.julia/environments/v1.0/Manifest.toml`
  [4d1e1d77] + Nullables v0.0.8
  [fcd29c91] ↓ QuantEcon v0.15.0 ⇒ v0.14.3

julia> using QuantEcon

julia> pathof(QuantEcon)
"/home/jupyter/.julia/packages/QuantEcon/tkpvN/src/QuantEcon.jl"
```

3. Yup. 

```
julia> pathof(Flux)
"/home/jupyter/.julia/packages/Flux/UHjNa/src/Flux.jl"
```

4. The only thing here is that it won't work unless `IJulia` is in the user's manifest. (and this is prior to activating any particular Jupyter cell). 

Other than that, this works as expected. For example, running the Kalman notebook from the `test_notebooks` will only make minor changes to account for the diff between the Manifest there and our latest one.
