### ISSUE TITLE
Using the new instantiation infrastructure

### ISSUE THREAD

**Issue by jlperla** [ubcecon/syzygy#4]
The current setup does something like this
```
# Set up our QuantEcon environment in the first depot entry for jovyan (~/jovyan/.julia). 
RUN mkdir -p $HOME/.julia/environments/v1.0 
# Instantiate everything we need. 
RUN cd $HOME/.julia/environments/v1.0 \
# Grab the online TOML. 
&& wget -q https://raw.githubusercontent.com/QuantEcon/lecture-source-jl/master/notebooks/Manifest.toml -O Manifest.toml \
&& wget -q https://raw.githubusercontent.com/QuantEcon/lecture-source-jl/master/notebooks/Project.toml -O Project.toml

# Set up our environment. 
RUN julia -e "using Pkg; pkg\"build\"; pkg\"instantiate\"; pkg\"precompile\""
```
Which I think is wrong on several levels.
- First, should let julia create its own environment/v1.0 as that is not our job.  I would be very worried that we are skipping over some setup and package things that it would normally do
- Second, we will want to be able to instantiate multiple versions of the lecture sources and other packages that have nothing to do with the QuantEcon lecture notes.

If I had to guess, the right way to do this is something that looks more like
```
RUN julia -e "using Pkg; pkg\"add IJulia InstantiateFromURL Compat Revise Plots Parameters GR; precompile\"
```
The goal there is to get some key pacakages installed and precompiled that we would want to use without having any Project files.

After that, we can activate/etc. whatever other stuff we want.  With the new InstantiateFromURL package, we would probably want to go
```
activate_github("QuantEcon/QuantEconLecturePackages")
activate_github("QuantEcon/QuantEconLecturePackages", "v0.1")
activate_github("QuantEcon/QuantEconLecturePackages", "v0.2")
```
Which would ensure that the package versions for the master, 0.1, and 0.2 versions of the QE lectures are precompiled.

**Comment by jlperla** [comment]
Can use `] add ` from the URL for InstantiateFromURL for now/

**Comment by arnavs** [comment]
Done
